# Sleek, minimal and fast prompt configuration
format = """
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$character"""

add_newline = false

[character]
success_symbol = "[❯](bold #B9F2FF) "
error_symbol = "[❯](bold #F44336) "

[directory]
style = "bold #4A6A80"
truncate_to_repo = true
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = " "
style = "bold #B9F2FF"
format = "on [$symbol$branch]($style) "

[git_status]
style = "bold #F44336"
format = "([\\[$all_status$ahead_behind\\]]($style) )"

[cmd_duration]
min_time = 1000
format = "took [$duration](bold #FFC107) "
